abstract class appstates{}
class initialstate extends appstates{}
class   successstateshow extends appstates{}
class   loadingstateregister extends appstates{}
class   successstateregister extends appstates{}
class   errorstateregister extends appstates{}
class   loadingstatelogin extends appstates{}
class   successstatelogin extends appstates{}
class   errorstatelogin extends appstates{}
class   loadingstatecategories extends appstates{}
class   successstatecategories extends appstates{}
class   errorstatecategories extends appstates{}
class   loadingstateproduct extends appstates{}
class   successstateproduct extends appstates{}
class   errorstateproduct extends appstates{}
class   changepagesstate extends appstates{}
class   changecolorfavouitestate extends appstates{}
class   successincrementstate extends appstates{}
class   successdecrementstate extends appstates{}
class   loadingstateorder extends appstates{}
class   successstateorder extends appstates{}
class   errorstateorder extends appstates{}
class   LoadingStateAddToCart extends appstates{}
class   SuccessStateAddToCart extends appstates{}
class   ErrorStateAddToCart extends appstates{}
class   LoadingStategetcartt extends appstates{}
class   SuccessStategetcartt extends appstates{}
class   ErrorStategetcartt extends appstates{}
class   LoadingStategetsearch extends appstates{}
class   SuccessStategetsearch extends appstates{}
class   ErrorStategetsearch extends appstates{}